---
# Copyright (c) 2016 Christian Saide <Supernomad>
# Licensed under the MPL-2.0, for details see https://github.com/Supernomad/quantum/blob/master/LICENSE

language: go

sudo: true

go:
  - 1.7.x

script:
  - sudo -i -E bash -c "cd $(pwd) && make full"
#  - make PUSH_COVERAGE="push" ci
